# Generated by Django 4.2.5 on 2023-09-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('socket', models.CharField(max_length=20)),
            ],
        ),
    ]
