# Generated by Django 4.2.5 on 2023-09-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('chipset', models.CharField(max_length=255)),
                ('socket', models.CharField(max_length=255)),
            ],
        ),
    ]
