# Generated by Django 4.2.5 on 2023-09-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_ram_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='Freq',
            field=models.IntegerField(),
        ),
    ]
