# Generated by Django 4.2.5 on 2023-09-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_ram_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='mb',
            name='DDR_Type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
