# Generated by Django 4.2.5 on 2023-09-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_mb_ddr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='Capacity',
            field=models.CharField(choices=[('8gb', ' 8')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='Vendor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
