# Generated by Django 4.2.5 on 2023-09-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_ram_capacity_ram_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='Capacity',
            field=models.CharField(choices=[('8gb', '8Гб (1x8Гб)'), ('16gbx1', '16Гб (1x16Гб)'), ('16gbx2', '16Гб (2x8Гб)'), ('32gbx1', '32Гб (1x32Гб)'), ('32gbx2', '32Гб (2x16Гб)')], max_length=20, null=True),
        ),
    ]
