# Generated by Django 4.2.5 on 2023-09-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_ram_model_alter_ram_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='Timing',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='Type',
            field=models.CharField(choices=[('4', 'DDR4'), ('5', 'DDR5')], max_length=25, null=True),
        ),
    ]
