# Generated by Django 4.2.5 on 2023-09-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_ram_timing_alter_ram_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('Type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=4)),
            ],
        ),
    ]
