# Generated by Django 4.2.5 on 2023-09-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='Type',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('M2', 'M2')], max_length=10),
        ),
    ]
