# Generated by Django 4.2.5 on 2023-09-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_storage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mb',
            name='M2_sum',
            field=models.SmallIntegerField(null=True),
        ),
    ]
