# Generated by Django 4.2.5 on 2023-09-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_mb_m2_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='Type',
            field=models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=25, null=True),
        ),
    ]
