# Generated by Django 4.2.5 on 2023-09-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_gpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='type',
            field=models.CharField(choices=[('APU', 'APU'), ('CPU', 'CPU')], default='CPU', max_length=5),
        ),
    ]
