# Generated by Django 4.2.5 on 2023-09-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_cpu_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('power', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Блок питания',
                'verbose_name_plural': 'Блоки питания',
            },
        ),
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'Процессор', 'verbose_name_plural': 'Процессоры'},
        ),
        migrations.AlterModelOptions(
            name='gpu',
            options={'verbose_name': 'Вмдеокарта', 'verbose_name_plural': 'Вмдеокарты'},
        ),
        migrations.AlterModelOptions(
            name='mb',
            options={'verbose_name': 'Материнская плата', 'verbose_name_plural': 'Материнские платы'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'Оперативная память', 'verbose_name_plural': 'Оперативная память'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Жесткий диск', 'verbose_name_plural': 'Жесткие диски'},
        ),
    ]
