# Generated by Django 4.2.5 on 2023-09-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_psu_alter_cpu_options_alter_gpu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mb',
            name='form_factor',
            field=models.CharField(choices=[('Mini-ITX ', 'Mini-ITX '), ('Micro-ATX ', 'Micro-ATX '), ('ATX', 'ATX'), ('E-ATX', 'E-ATX')], default='ATX', max_length=30),
        ),
    ]
