# Generated by Django 4.2.5 on 2023-09-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('pc_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='CPU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.cpu'),
        ),
    ]
