# Generated by Django 4.2.5 on 2023-09-07 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_mb'),
        ('pc_config', '0002_alter_build_cpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='MB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.mb'),
        ),
    ]
