# Generated by Django 4.2.5 on 2023-09-16 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_ram_freq'),
        ('pc_config', '0003_build_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='Ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ram'),
        ),
    ]
