# Generated by Django 4.2.5 on 2023-09-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_gpu'),
        ('pc_config', '0005_build_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='GPU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.gpu'),
        ),
    ]
