# Generated by Django 4.2.5 on 2023-09-18 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_psu_alter_cpu_options_alter_gpu_options_and_more'),
        ('pc_config', '0006_build_gpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='PSU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.psu'),
        ),
    ]
