# Generated by Django 4.2.5 on 2023-09-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_config', '0007_build_psu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'verbose_name': 'Материнская плата', 'verbose_name_plural': 'Материнские платы'},
        ),
    ]
